server:
  port: ${PORT:5000}

base-url: /api

spring:
  application:
    name: app
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop

jwt:
  issuer: app
  expiration-sec: 86400
  clock-skew-sec: 300
  secret: secret