server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    username: sa
    password:
    url: "jdbc:h2:./database"
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2console/

logging:
  level:
    root: INFO
    web: DEBUG
